[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Enable branch deploys for all branches
[context.branch-deploy]
  command = "npm run build"

# Enable deploy previews for pull requests
[context.deploy-preview]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
